site_name: 学院档案馆
site_description: CyanStars 附属文档站点
site_author: 无圻寻光开发组
site_url: https://IPOL-Studio.github.io/CyanStars_Docs
repo_url: https://github.com/IPOL-Studio/CyanStars_Docs
theme:
  name: material
  custom_dir: overrides
  language: zh
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.tabs
  - navigation.prune
  - navigation.indexes
  - toc.follow
  - toc.integrate
  - navigation.top
  - search.suggest
  - content.code.copy
  - content.tooltips
  palette: 
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    accent: indigo
    toggle:
      icon: material/brightness-7 
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    accent: indigo
    toggle:
      icon: material/brightness-4

extra:
  generator: false
  alternate:
  - name: 简体中文
    link: /CyanStars_Docs/
    lang: zh
  - name: 繁體中文
    link: /CyanStars_Docs/zh-Hant/
    lang: zh-Hant
  - name: English
    link: /CyanStars_Docs/en/
    lang: en
  - name: 日本語
    link: /CyanStars_Docs/ja/
    lang: ja

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
- home: index.md
- database: 
  - contributions: database/contributions.md
  - list-of-included-music: database/list-of-included-music.md

plugins:
- search:
    separator: '[\s\u200b\-]'
- i18n:
    docs_structure: folder
    fallback_to_default: true
    reconfigure_material: true
    reconfigure_search: true
    languages:
    - locale: zh
      build: true
      default: true
      name: 简体中文
      site_name: 学院档案馆
      nav_translations:
        home: 主页
        database: 资料库
        contributions: 贡献者列表
        list-of-included-music: 收录曲列表
    - locale: zh-Hant
      build: true
      name: 繁體中文
      site_name: 學院檔案館
      nav_translations:
        home: 主頁
    - locale: en
      build: true
      name: English
      site_name: College Archives
      nav_translations:
        home: Home
        contributions: Contributions
        list-of-included-music: List of included music
    - locale: ja
      build: true
      name: 日本語
      site_name: 学院ファイル館
      nav_translations:
        home: ホーム